# -*- coding: utf-8 -*-
"""Exercício módulo 01 - Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vHSHLjSmiBttrCbxMNfuFXbsM2nLCV43
"""

# Variável para controlar a calculadora

calculadora = True

# Loop principal

while calculadora:

    # Verificação do primeiro número
    while True:

        try:

            num1 = input("Digite o primeiro número: ")

            # Converte para número Real
            num1 = float(num1)

            # Converte para número Inteiro
            if num1.is_integer():
                num1 = int(num1)

            # Sai do loop de verificação se estiver correto
            break

        except ValueError:
            print("Não é um número válido. Tente novamente.")

    # Verificação do segundo número
    while True:

        try:

            num2 = input("Digite o segundo número: ")

            # Converte para número Real
            num2 = float(num2)

            # Converte para número Inteiro
            if num2.is_integer():
                num2 = int(num2)

            # Sai do loop de verificação se estiver correto
            break

        except ValueError:
            print("Não é um número válido. Tente novamente.")

    # Escolha da operação matemática

    print("\nEscolha a operação:")
    print("1 - Soma")
    print("2 - Subtração")
    print("3 - Multiplicação")
    print("4 - Divisão")

    opcao = input("Digite a opção desejada: ")

    if opcao == "1":
        resultado = num1 + num2
        print(f"O resultado da soma é: {resultado}")

    elif opcao == "2":
        resultado = num1 - num2
        print(f"O resultado da subtração é: {resultado}")

    elif opcao == "3":
        resultado = num1 * num2
        print(f"O resultado da multiplicação é: {resultado}")

    elif opcao == "4":

        if num2 != 0:
            resultado = num1 / num2
            print(f"O resultado da divisão é: {resultado}")

        else:
            print("Não é possível dividir por zero.")

    else:
        print("Opção inválida. Tente novamente.")

    # Loop da continuação da calculadora

    while True:

        continuar = input("Deseja continuar a calcular? (s/n): ").lower()

        if continuar == "s":

            # Parar o Loop interno
            break

        elif continuar == "n":

            print("Calculadora encerrada.")

      # Loop principal
            calculadora = False

            # Parar o Loop interno
            break

        else:
            print(print("Opção inválida. Favor digitar 's' para continuar ou 'n' para encerrar a calculadora."))

